### ISSUE TITLE
Error in model.frame.default(formula = kappa ~ 1, na.action = na.pass) :    object is not a matrix

### ISSUE THREAD

**Issue by Longevitas** [spkaluzny/robustarima#1]
The following R script produces the error message in the title:

```
# Create two time series with different trends
n <- 20
set.seed(-1)
kappa1 <- cumsum(-0.01+rnorm(n, sd=0.01))
kappa2 <- cumsum(-0.04+rnorm(n, sd=0.01))

# Combine them to create a single broken-trend series
kappa <- c(kappa1, kappa1[n]+kappa2)

# Examine broken trend
plot(kappa)

# Now fit using robust ARIMA package.
library("robustarima")
Model <- arima.rob(kappa~1, d=1)
```

If you change the object in the `arima.rob()` call from `kappa` to either `kappa1` or `kappa2`, then the model fits fine.

**Comment by spkaluzny** [comment]
This is a problem with how arima.rob evaluates its formula - it is not using the proper environment when doing the `eval`. In this case, it is finding the function `base::kappa` instead of the vector `kappa` that was defined.

I have fixed this bug in the current `robustarima` here on Github. You can install directly from Github with:
`devtools::install_github("spkaluzny/robustarima")`
If you are on Windows, you will need to have set up Rtools since the package is being installed from source.

The new version should appear on CRAN soon.
